# Generated by Django 5.2.10 on 2026-01-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
