# Generated by Django 5.2.10 on 2026-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_rename_categories_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=200)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_it_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
