# Generated by Django 5.2.10 on 2026-01-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'ordering': ['look_price'], 'verbose_name': 'Comparativa de Precio'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
