# Generated by Django 5.2.10 on 2026-01-29 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_alter_compare_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnitPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad (Gramos)')),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Granel')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_pricing', to='registers.product')),
            ],
            options={
                'verbose_name': 'Precio al Detalle',
                'verbose_name_plural': 'Precios al Detalle',
            },
        ),
    ]
